export const IPC = {
  AppGetVersion: 'app:getVersion',
  AppGetPlatform: 'app:getPlatform',
  WindowMinimize: 'window:minimize',
  WindowMaximize: 'window:maximize',
  WindowClose: 'window:close',
  WindowIsMaximized: 'window:isMaximized',
  WindowMaximizeChange: 'window:maximize-change',
  FileSelectFiles: 'file:selectFiles',
  FileSelectFolder: 'file:selectFolder',
  FileSaveAs: 'file:saveAs',
  FileRead: 'file:read',
  FileWrite: 'file:write',
  FileExtractWrite: 'file:extractWrite',
  FileStat: 'file:stat',
  FileApprovePaths: 'file:approvePaths',
  FileClearApprovals: 'file:clearApprovals',
  FileGetTempDir: 'file:getTempDir',
  FileSaveOutput: 'file:saveOutput',
  FileSaveOutputFile: 'file:saveOutputFile',
  FileSaveAsFile: 'file:saveAsFile',
  FileCleanupJobTemp: 'file:cleanupJobTemp',
  ShellOpenPath: 'shell:openPath',
  ShellShowItemInFolder: 'shell:showItemInFolder',
  NotifyShow: 'notify:show',
  UpdateCheck: 'update:check',
  UpdateDownload: 'update:download',
  UpdateInstall: 'update:install',
  UpdateStatus: 'update:status',
  EngineRun: 'engine:run',
  EngineCancel: 'engine:cancel',
  EngineProgress: 'engine:progress',
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]